#!/bin/bash

echo "🚀 Швидке розгортання калькулятора сейфу на Vercel"
echo "================================================="
echo ""
echo "📌 Варіанти розгортання:"
echo ""
echo "1️⃣  Один клік (рекомендується):"
echo "   https://vercel.com/new/clone?repository-url=https://github.com/Quick-coder123/safe&project-name=safe-calculator&root-directory=web-app"
echo ""
echo "2️⃣  Через Vercel CLI:"
echo "   cd web-app"
echo "   npm i -g vercel"
echo "   vercel"
echo ""
echo "3️⃣  Через GitHub:"
echo "   1. Fork цього репозиторію"
echo "   2. Підключити до Vercel"
echo "   3. Root Directory: web-app"
echo "   4. Deploy"
echo ""
echo "📱 Після розгортання ваш сайт буде доступний на:"
echo "   https://your-project-name.vercel.app"
echo ""
echo "✅ Готово до використання!"
